require("prototypes.buildings.forge-roboport")
require("prototypes.buildings.forge-assembly-hatch")
require("prototypes.buildings.cube-processing-plant")
require("prototypes.buildings.forge-export-bus")
require("prototypes.buildings.cube-sauna")
